 DROP TABLE IF EXISTS user;
 DROP TABLE IF EXISTS entries;
 
 CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL
);

CREATE TABLE entries (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	author_id INTEGER NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	field1 TEXT NOT NULL,
	field2 TEXT NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id)
);